image: golang:1.11-alpine3.9

cache:
  paths:
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

variables:
   DOCKER_HOST: tcp://docker:2375/
   DOCKER_REPOSITORY: mendersoftware/mender-artifact
   S3_BUCKET_NAME: "mender"
   S3_BUCKET_PATH: "mender-artifact"

services:
  - docker:19.03.5-dind

stages:
  - test
  - build
  - publish
  - integration

before_script:
  - mkdir -p /go/src/github.com/mendersoftware /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/github.com/mendersoftware/mender-artifact
  - ln -s /go/src/github.com/mendersoftware /go/src/_/builds/mendersoftware
  - cd /go/src/github.com/mendersoftware/mender-artifact
  - apk update && apk add git make
  # Install code coverage tooling
  - make get-tools

test:static:
  stage: test
  script:
    - apk add bash dosfstools e2fsprogs e2fsprogs-extra gcc libc6-compat mtools musl-dev parted perl-utils xz-dev
    - make extracheck
    - make coverage
    - mv /go/src/github.com/mendersoftware/mender-artifact/coverage.txt $CI_PROJECT_DIR/coverage.txt
  artifacts:
    expire_in: 2w
    untracked: true
    paths:
      - coverage.txt

build:docker:
  image: docker
  before_script: []
  stage: build
  script:
    - docker build -t $DOCKER_REPOSITORY:pr .
    - docker save $DOCKER_REPOSITORY:pr > image.tar
  artifacts:
    expire_in: 2w
    paths:
      - image.tar
  tags:
    - docker

build:make:
  image: docker
  before_script:
    - apk add --no-cache make
  stage: build
  script:
    - make build-natives-contained
  artifacts:
    expire_in: 2w
    paths:
      - mender-artifact-*
  tags:
    - docker

publish:tests:
  image: alpine
  stage: publish
  before_script:
    - apk add --no-cache bash curl findutils git
  dependencies:
    - test:static
  script:
    - bash -c "bash <(curl -s https://codecov.io/bash) -Z"

publish:s3:
  stage: publish
  image: debian:buster
  dependencies:
    - build:make
  before_script:
    - apt update && apt install -yyq awscli
  script:
    - for bin in mender-artifact-darwin mender-artifact-linux mender-artifact-windows.exe; do
        platform=${bin#mender-artifact-};
        platform=${platform%.*};
        echo "Publishing ${CI_COMMIT_REF_NAME} version for ${platform} to S3";
        aws s3 cp ${bin}
          s3://$S3_BUCKET_NAME/$S3_BUCKET_PATH/${CI_COMMIT_REF_NAME}/${platform}/mender-artifact;
        aws s3api put-object-acl --acl public-read --bucket $S3_BUCKET_NAME
          --key $S3_BUCKET_PATH/${CI_COMMIT_REF_NAME}/${platform}/mender-artifact;
      done
  only:
    - /^(master|[0-9]+\.[0-9]+\.x)$/
